# Generated by Django 5.0.2 on 2024-02-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_distance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distance',
            unique_together={('origin', 'destination')},
        ),
    ]
